# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igad_geonode', '0014_remove_menuitem_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicalkeywordmeta',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'img/%Y/%m'),
        ),
    ]
